"""Recreate schema

Revision ID: 02239e18a3f0
Revises: 178a8a43149f
Create Date: 2024-11-21 20:35:59.721967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02239e18a3f0'
down_revision = '178a8a43149f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    def upgrade():
    # Alter columns
    with op.batch_alter_table('chatbox', schema=None) as batch_op:
        batch_op.alter_column('user_id_1',
                              existing_type=mysql.INTEGER(),
                              nullable=False)
        batch_op.alter_column('user_id_2',
                              existing_type=mysql.INTEGER(),
                              nullable=False)
    
    # Add new foreign key constraints with cascading behavior
    with op.batch_alter_table('chatbox', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_user1', 'user', ['user_id_1'], ['user_id'], ondelete='CASCADE'
        )
        batch_op.create_foreign_key(
            'fk_user2', 'user', ['user_id_2'], ['user_id'], ondelete='CASCADE'
        )


    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('post_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.create_foreign_key(None, 'comment', ['parent_comment_id'], ['comment_id'])

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('end_time',
               existing_type=mysql.DATETIME(),
               nullable=False)

    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.alter_column('user_id_1',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id_2',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('groupmembership', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('group_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('post_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('sender_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('receiver_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=False)
        batch_op.alter_column('chatbox_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.alter_column('tagged_user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('post_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('tagged_user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('chatbox_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=True)
        batch_op.alter_column('receiver_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('sender_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('post_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('groupmembership', schema=None) as batch_op:
        batch_op.alter_column('group_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.alter_column('user_id_2',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id_1',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('start_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('post_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('chatbox', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user1', type_='foreignkey')
        batch_op.drop_constraint('fk_user2', type_='foreignkey')
    
    with op.batch_alter_table('chatbox', schema=None) as batch_op:
        batch_op.alter_column('user_id_2',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id_1',
               existing_type=mysql.INTEGER(),
               nullable=True)
    
    # Recreate foreign key constraints
    with op.batch_alter_table('chatbox', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user1', 'user', ['user_id_1'], ['user_id'])
        batch_op.create_foreign_key('fk_user2', 'user', ['user_id_2'], ['user_id'])

    # ### end Alembic commands ###
